### ISSUE TITLE
backlog optimization: look into adjusting bitwise constraints to integer constraints to reduce total circom constraints

### ISSUE THREAD

**Issue by thor314** [pluto/aes-proof#63] opened 2024-09-05 23:16 UTC
We have implemented galois multiplication for ghash at the bit level; this may require more circuit gate constraints
than completely necessary.

A possible optimization path for proving would look to adjust bitwise constraints to integer-wise constraints where
possible.

**Comment by brunny-eth** [comment] 2024-09-09 20:04
---
name: adjust bitwise constraints to integer constraints to reduce total circuit constraints
about: optimize AES-GCM proof implementation by converting bitwise constraints to integer constraints where possible
title: optimization by adjusting bitwise constraints to integer constraints
labels: Bounty 💰
assignees:

---

**Bounty description**

Optimize the AES-GCM proof implementation by converting bitwise constraints to integer constraints where possible, with a focus on the Galois multiplication used in ghash. The goal is to reduce the total number of circuit gate constraints.

**Implementation requirements**

- [ ] Identify relevant areas where bitwise operations are used, and determine which can be converted to integer operations
- [ ] Implement integer-based Galois multiplication for ghash 
- [ ] Modify existing circuits to incorporate new integer-based operations
    - Update dependent circuits/components as necessary
- [ ] Test suite, documentation, and benchmarking
    - Ensure optimized circuits produce correct results
    - Verify against test vectors for AES-GCM
    - Measure and document reduction in constraint count vs existing implementation
    - Proper code commenting and documentation to reflect changes and optimizations
     
**Bonus features**

Any additional features that will enhance the value of the bounty. 

- [ ] Extend optimization to other parts of the implementation if applicable
- [ ] Implement parametrized version that allows switching between the bitwise and integer-based implementations
- [ ] Provide a short but detailed analysis of the trade-offs between bitwise and integer approaches


**Resources**

[Circom Documentation](https://docs.circom.io/)
[Efficient zero-knowledge circuits for GCM](https://eprint.iacr.org/2022/1303.pdf)
[NIST SP 800-38D (GCM mode)](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf)
[Optimizing Arithmetic Circuits for ZKPs](https://www.zksecurity.xyz/blog/posts/optimizing-arithmetic-circuits/)

**Criteria**

Bounties will be rewarded based on the following criteria:

1. Correctness and security: A thorough review of the implementation should convince our team that they are correct and secure, with all requirements met.
2. Code clarity and quality: Succinct, easy-to-follow code with appropriate naming conventions. Utilize Rust’s type system for flexibility and security (e.g., compile-time checks where possible), and avoid external crates. Optimizations should be a lower priority than clarity, but can be included behind a feature flag as a bonus.
3. Documentation quality: Provide comprehensive README’s, Cargo docs, and inline comments where code itself is not self-explanatory. Prioritize clarity and readability.

**Comment by brunny-eth** [comment] 2024-09-09 20:04
@thor314  this is my attempt at turning this into a proper bounty, please provide feedback or update the issue with this if appropriate!

cc: @Autoparallel + @0xJepsen

**Comment by devloper** [comment] 2024-10-16 05:11
duplicate of #95

**Closed by devloper** 2024-10-16 05:11 UTC
