### ISSUE TITLE
bug: allow for `circom-witnesscalc` `build-circuit` to work

### ISSUE THREAD

**Issue by Autoparallel** [pluto/aes-proof#92] opened 2024-10-15 18:04 UTC
In our proof stack, we want to get the `build-circuit` command from [`circom-witnesscalc`](https://github.com/iden3/circom-witnesscalc) to run with `aes-gcm-fold.circom`. 

Based on the main branch, this does not work.

**Comment by devloper** [comment] 2024-10-16 05:07
Looks like a duplicate of: https://github.com/pluto/web-prover/issues/215

**Closed by devloper** 2024-10-16 05:07 UTC
